import { jsPDF } from "jspdf";

/* ------------------------------------------------------------------ *
 * Client-side receipt PDFs (#2). Plain jsPDF text layout — no server
 * storage. Used after a successful issue/return and for re-printing from
 * the officer profile. Both builders share the same header/footer style.
 * ------------------------------------------------------------------ */

export type ReceiptLine = {
  itemName: string;
  category?: string | null;
  sizeOrVariant?: string | null;
  /** Pre-formatted serial(s) — "FP … / BP …" for dual-serial units. */
  serials?: string | null;
  quantity: number;
  condition?: string | null;
};

export type IssueReceiptData = {
  timestamp: string;
  /** ISO issuance datetime — used only for the PDF filename date (#7). */
  issuedAt?: string | null;
  officerName: string;
  badgeNumber: string;
  issuedBy?: string | null;
  issuedLocation?: string | null;
  dueDate?: string | null;
  /** Typed acknowledgement text, or a captured signature image data URL. */
  signature?: string | null;
  lines: ReceiptLine[];
};

export type ReturnReceiptData = {
  timestamp: string;
  officerName: string;
  badgeNumber: string;
  returnedBy?: string | null;
  conditionIn?: string | null;
  lines: ReceiptLine[];
};

const MARGIN = 14;
const LINE = 6;

function header(doc: jsPDF, title: string): number {
  const w = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("UFPD Quartermaster", w / 2, 16, { align: "center" });
  doc.setFontSize(12);
  doc.text(title, w / 2, 24, { align: "center" });
  doc.setDrawColor(180);
  doc.line(MARGIN, 28, w - MARGIN, 28);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  return 36;
}

function footer(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text(`Page ${p} of ${pages}`, w - MARGIN, h - 8, { align: "right" });
    doc.text("Generated by UFPD Quartermaster", MARGIN, h - 8);
    doc.setTextColor(0);
  }
}

function kv(doc: jsPDF, y: number, label: string, value: string): number {
  doc.setFont("helvetica", "bold");
  doc.text(label, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.text(value, MARGIN + 34, y);
  return y + LINE;
}

// Draw a simple text table for the receipt lines. Returns the new y.
function lineTable(doc: jsPDF, y: number, lines: ReceiptLine[]): number {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Item", MARGIN, y);
  doc.text("Category", MARGIN + 60, y);
  doc.text("Size/Serial", MARGIN + 95, y);
  doc.text("Qty", w - MARGIN - 22, y);
  doc.text("Cond", w - MARGIN - 12, y);
  y += 2;
  doc.setDrawColor(200);
  doc.line(MARGIN, y, w - MARGIN, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  for (const l of lines) {
    if (y > h - 20) { doc.addPage(); y = 20; }
    const detail = [l.sizeOrVariant, l.serials].filter(Boolean).join(" · ") || "—";
    const itemLines = doc.splitTextToSize(l.itemName, 55);
    const detailLines = doc.splitTextToSize(detail, 55);
    doc.text(itemLines, MARGIN, y);
    doc.text(l.category || "—", MARGIN + 60, y);
    doc.text(detailLines, MARGIN + 95, y);
    doc.text(String(l.quantity), w - MARGIN - 22, y);
    doc.text(l.condition || "—", w - MARGIN - 12, y);
    const rows = Math.max(itemLines.length, detailLines.length, 1);
    y += LINE * rows;
  }
  return y;
}

export function buildIssueReceipt(data: IssueReceiptData): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = header(doc, "Equipment Issue Receipt");
  y = kv(doc, y, "Receipt time", data.timestamp);
  y = data.badgeNumber
    ? kv(doc, y, "Officer", `${data.officerName} (#${data.badgeNumber})`)
    : kv(doc, y, "Recipient", data.officerName);
  if (data.issuedBy) y = kv(doc, y, "Issued by", data.issuedBy);
  if (data.issuedLocation) y = kv(doc, y, "Issued location", data.issuedLocation);
  if (data.dueDate) y = kv(doc, y, "Due date", data.dueDate);
  y += 3;
  y = lineTable(doc, y, data.lines);
  y += 8;
  const w = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Recipient signature:", MARGIN, y);
  if (data.signature && /^data:image\//.test(data.signature)) {
    try { doc.addImage(data.signature, "PNG", MARGIN + 42, y - 6, 50, 16); } catch { /* ignore bad image */ }
  } else if (data.signature) {
    doc.setFont("helvetica", "italic");
    doc.text(data.signature, MARGIN + 42, y);
  }
  doc.setDrawColor(120);
  doc.line(MARGIN + 40, y + 2, w - MARGIN, y + 2);
  footer(doc);
  return doc;
}

export function buildReturnReceipt(data: ReturnReceiptData): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = header(doc, "Equipment Return Receipt");
  y = kv(doc, y, "Receipt time", data.timestamp);
  y = data.badgeNumber
    ? kv(doc, y, "Officer", `${data.officerName} (#${data.badgeNumber})`)
    : kv(doc, y, "Recipient", data.officerName);
  if (data.returnedBy) y = kv(doc, y, "Returned by", data.returnedBy);
  if (data.conditionIn) y = kv(doc, y, "Condition in", data.conditionIn);
  y += 3;
  lineTable(doc, y, data.lines);
  footer(doc);
  return doc;
}

function slug(s: string) { return s.replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, ""); }

// YYYY-MM-DD in local time. Falls back to today when no/invalid date is given.
function fileDate(iso?: string | null): string {
  const d = iso ? new Date(iso) : new Date();
  const dt = isNaN(d.getTime()) ? new Date() : d;
  const m = String(dt.getMonth() + 1).padStart(2, "0");
  const day = String(dt.getDate()).padStart(2, "0");
  return `${dt.getFullYear()}-${m}-${day}`;
}

// Preserve spaces (the required format has them) but strip characters that are
// invalid in filenames on Windows/macOS/Linux, plus control chars.
function sanitizeFilename(s: string): string {
  return s.replace(/[\/\\:*?"<>|\x00-\x1f]/g, "").replace(/\s+/g, " ").trim();
}

export function downloadIssueReceipt(data: IssueReceiptData) {
  const name = sanitizeFilename(data.officerName) || "Recipient";
  buildIssueReceipt(data).save(`${fileDate(data.issuedAt)}_Items Issued_${name}.pdf`);
}

export function downloadReturnReceipt(data: ReturnReceiptData) {
  buildReturnReceipt(data).save(`return_receipt_${slug(data.officerName)}_${Date.now()}.pdf`);
}
