-- Batch 4 (Jul 2026): email_log table for the provider-agnostic email subsystem.
-- Applied to dev and prod as migration "batch4_email_log".
-- Run AFTER migration.sql + hardening.sql (requires private.app_authorized()).

CREATE TABLE IF NOT EXISTS email_log (
  "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient"   text NOT NULL,
  "subject"     text NOT NULL,
  "body"        text NOT NULL,
  "template"    text,
  "status"      text NOT NULL DEFAULT 'logged',   -- 'logged' | 'sent' | 'failed'
  "provider"    text NOT NULL DEFAULT 'log',      -- 'log' | 'resend' | 'smtp'
  "error"       text,
  "relatedType" text,
  "relatedId"   integer,
  "createdAt"   text NOT NULL
);

CREATE INDEX IF NOT EXISTS email_log_created_idx ON email_log ("createdAt");

-- Same RLS gate as every other application table (x-app-secret header check).
ALTER TABLE public.email_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_all ON public.email_log;
CREATE POLICY app_all ON public.email_log FOR ALL TO anon
  USING ((SELECT private.app_authorized()))
  WITH CHECK ((SELECT private.app_authorized()));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.email_log TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
