-- ============================================================================
-- UFPD Quartermaster — Supabase (Postgres 17) schema + atomic operations
--
-- Translated from shared/schema.ts (Drizzle sqlite-core). Design notes:
--   * Column identifiers are QUOTED camelCase (e.g. "badgeNumber") so that
--     supabase-js / PostgREST round-trips the exact JS key names the app and
--     frontend already use — no snake_case<->camelCase mapping layer, and
--     JSON responses stay byte-for-byte identical.
--   * Integer PKs use GENERATED BY DEFAULT AS IDENTITY so a data migration can
--     insert rows with their existing IDs, after which sequences are reset
--     (see reset_sequences()).
--   * booleans map to Postgres boolean; "unitCost" uses double precision to
--     match SQLite's 8-byte REAL (avoids float4 drift on values like 2.3).
--   * RLS is intentionally left DISABLED (the app is the authorization
--     boundary via its own bcrypt/bearer-token auth; Supabase Auth is unused).
--   * FK ON DELETE behavior replicates the app's delete-cascade expectations:
--     deleting an item removes its units/variants/assignments; deleting an
--     officer removes their assignments; deleting a kit removes its kit_items.
--     Soft links (assignments -> unit/variant) SET NULL so returned-history
--     rows survive a unit/variant deletion.
--   * Every multi-statement / transactional operation in the storage layer is
--     expressed as a plpgsql function (SECURITY INVOKER) so it runs atomically
--     inside a single transaction, invoked from the server via supabase.rpc().
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Tables (created in FK-dependency order)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS officers (
  "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "badgeNumber" text NOT NULL,
  "firstName"   text NOT NULL,
  "lastName"    text NOT NULL,
  "rank"        text,
  "unit"        text,
  "email"       text,
  "phone"       text,
  "status"      text NOT NULL DEFAULT 'active',
  "type"        text NOT NULL DEFAULT 'person',
  "hireDate"    text,
  "shirtSize"   text,
  "pantsSize"   text,
  "jacketSize"  text,
  "shoeSize"    text,
  "vestSize"    text,
  "hatSize"     text,
  "gloveSize"   text,
  "notes"       text
);

CREATE TABLE IF NOT EXISTS users (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username"           text NOT NULL,
  "password"           text NOT NULL,
  "name"               text NOT NULL,
  "role"               text NOT NULL DEFAULT 'auditor',
  "officerId"          integer REFERENCES officers("id") ON DELETE SET NULL,
  "mustChangePassword" boolean NOT NULL DEFAULT false,
  "active"             boolean NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users ("username");

CREATE TABLE IF NOT EXISTS items (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"               text NOT NULL,
  "category"           text NOT NULL DEFAULT 'General',
  "subcategory"        text,
  "type"               text NOT NULL DEFAULT 'consumable',
  "sku"                text,
  "serialNumber"       text,
  "size"               text,
  "color"              text,
  "quantity"           integer NOT NULL DEFAULT 0,
  "parLevel"           integer NOT NULL DEFAULT 0,
  "location"           text,
  "unitCost"           double precision DEFAULT 0,
  "vendor"             text,
  "grantNumber"        text,
  "expirationDate"     text,
  "condition"          text DEFAULT 'New',
  "status"             text NOT NULL DEFAULT 'in_stock',
  "returnBehavior"     text DEFAULT 'returnable',
  "requiresInspection" boolean NOT NULL DEFAULT false,
  "requiresDualSerial" boolean NOT NULL DEFAULT false,
  "lastInspected"      text,
  "imageUrl"           text,
  "attributes"         text,
  "notes"              text,
  "createdAt"          text NOT NULL
);

CREATE TABLE IF NOT EXISTS item_units (
  "id"                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itemId"                 integer NOT NULL REFERENCES items("id") ON DELETE CASCADE,
  "serialNumber"           text NOT NULL,
  "secondarySerialNumber"  text,
  "status"                 text NOT NULL DEFAULT 'in_stock',
  "condition"              text DEFAULT 'New',
  "assignedOfficerId"      integer,
  "location"               text,
  "acquiredDate"           text,
  "notes"                  text,
  "createdAt"              text NOT NULL
);
CREATE INDEX IF NOT EXISTS item_units_item_id_idx ON item_units ("itemId");

CREATE TABLE IF NOT EXISTS item_variants (
  "id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itemId"    integer NOT NULL REFERENCES items("id") ON DELETE CASCADE,
  "size"      text NOT NULL,
  "sku"       text,
  "quantity"  integer NOT NULL DEFAULT 0,
  "parLevel"  integer NOT NULL DEFAULT 0,
  "notes"     text,
  "createdAt" text NOT NULL
);
CREATE INDEX IF NOT EXISTS item_variants_item_id_idx ON item_variants ("itemId");

CREATE TABLE IF NOT EXISTS assignments (
  "id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itemId"        integer NOT NULL REFERENCES items("id") ON DELETE CASCADE,
  "itemUnitId"    integer REFERENCES item_units("id") ON DELETE SET NULL,
  "itemVariantId" integer REFERENCES item_variants("id") ON DELETE SET NULL,
  "officerId"     integer NOT NULL REFERENCES officers("id") ON DELETE CASCADE,
  "quantity"      integer NOT NULL DEFAULT 1,
  "status"        text NOT NULL DEFAULT 'active',
  "conditionOut"  text DEFAULT 'New',
  "conditionIn"   text,
  "issuedAt"      text NOT NULL,
  "dueDate"       text,
  "returnedAt"    text,
  "issuedBy"      text,
  "issuedLocation" text,
  "returnedBy"    text,
  "signature"     text,
  "notes"         text
);
CREATE INDEX IF NOT EXISTS assignments_officer_id_idx ON assignments ("officerId");
CREATE INDEX IF NOT EXISTS assignments_item_id_idx ON assignments ("itemId");
CREATE INDEX IF NOT EXISTS assignments_status_idx ON assignments ("status");

CREATE TABLE IF NOT EXISTS kits (
  "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        text NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS kit_items (
  "id"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kitId"    integer NOT NULL REFERENCES kits("id") ON DELETE CASCADE,
  "itemId"   integer NOT NULL REFERENCES items("id") ON DELETE CASCADE,
  "quantity" integer NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS kit_items_kit_id_idx ON kit_items ("kitId");

CREATE TABLE IF NOT EXISTS audit_log (
  "id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action"    text NOT NULL,
  "entity"    text,
  "entityId"  integer,
  "detail"    text,
  "username"  text,
  "timestamp" text NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_log_timestamp_idx ON audit_log ("timestamp");

-- ---------------------------------------------------------------------------
-- Helper: re-derive a `unique` item's quantity/status from its serialized
-- units. Mirrors storage.syncItemQuantity exactly:
--   quantity = number of units; status flips between in_stock/issued based on
--   whether any unit is in_stock, but a manual maintenance/retired hold on the
--   item is never clobbered.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION sync_item_quantity(p_item_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_type    text;
  v_status  text;
  v_total   integer;
  v_instock integer;
BEGIN
  SELECT "type", "status" INTO v_type, v_status FROM items WHERE "id" = p_item_id;
  IF NOT FOUND OR v_type <> 'unique' THEN
    RETURN;
  END IF;
  SELECT count(*), count(*) FILTER (WHERE "status" = 'in_stock')
    INTO v_total, v_instock
    FROM item_units WHERE "itemId" = p_item_id;
  IF v_status IN ('in_stock', 'issued') THEN
    UPDATE items
       SET "quantity" = v_total,
           "status"   = CASE WHEN v_instock > 0 THEN 'in_stock' ELSE 'issued' END
     WHERE "id" = p_item_id;
  ELSE
    UPDATE items SET "quantity" = v_total WHERE "id" = p_item_id;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- issue_batch — atomic single/multi-line issue.
-- The server (planIssue) pre-resolves and aggregates all stock deltas and one
-- assignment row per line; this function only APPLIES them, so all writes land
-- together or not at all. Returns the created assignment rows (in request line
-- order) as a jsonb array so the server can audit + respond.
--
-- Payload shape:
--   { "variantDeltas": [{ "id": int, "newQty": int }],
--     "itemDeltas":    [{ "id": int, "newQty": int, "setIssued": bool }],
--     "unitIssues":    [{ "id": int, "officerId": int }],
--     "assignments":   [{ ...full assignment column set (camelCase) }] }
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION issue_batch(p jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  result jsonb;
BEGIN
  UPDATE item_variants
     SET "quantity" = d."newQty"
    FROM jsonb_to_recordset(COALESCE(p->'variantDeltas', '[]'::jsonb))
           AS d("id" integer, "newQty" integer)
   WHERE item_variants."id" = d."id";

  UPDATE items
     SET "quantity" = d."newQty",
         "status"   = CASE WHEN d."setIssued" THEN 'issued' ELSE items."status" END
    FROM jsonb_to_recordset(COALESCE(p->'itemDeltas', '[]'::jsonb))
           AS d("id" integer, "newQty" integer, "setIssued" boolean)
   WHERE items."id" = d."id";

  UPDATE item_units
     SET "status" = 'issued',
         "assignedOfficerId" = d."officerId"
    FROM jsonb_to_recordset(COALESCE(p->'unitIssues', '[]'::jsonb))
           AS d("id" integer, "officerId" integer)
   WHERE item_units."id" = d."id";

  -- NOTE: jsonb_to_recordset cannot be combined with WITH ORDINALITY when a
  -- column-definition list is supplied ("WITH ORDINALITY cannot be used with a
  -- column definition list"). Expand each element with jsonb_array_elements
  -- (single jsonb column, ORDINALITY allowed) and cast fields explicitly.
  WITH src AS (
    SELECT
      (a.elem->>'itemId')::integer        AS "itemId",
      (a.elem->>'itemUnitId')::integer    AS "itemUnitId",
      (a.elem->>'itemVariantId')::integer AS "itemVariantId",
      (a.elem->>'officerId')::integer     AS "officerId",
      (a.elem->>'quantity')::integer      AS "quantity",
       a.elem->>'status'                  AS "status",
       a.elem->>'conditionOut'            AS "conditionOut",
       a.elem->>'conditionIn'             AS "conditionIn",
       a.elem->>'issuedAt'                AS "issuedAt",
       a.elem->>'dueDate'                 AS "dueDate",
       a.elem->>'returnedAt'              AS "returnedAt",
       a.elem->>'issuedBy'                AS "issuedBy",
       a.elem->>'issuedLocation'          AS "issuedLocation",
       a.elem->>'returnedBy'              AS "returnedBy",
       a.elem->>'signature'               AS "signature",
       a.elem->>'notes'                   AS "notes",
       a.ord                              AS ord
      FROM jsonb_array_elements(COALESCE(p->'assignments', '[]'::jsonb))
             WITH ORDINALITY AS a(elem, ord)
  ),
  ins AS (
    INSERT INTO assignments
      ("itemId","itemUnitId","itemVariantId","officerId","quantity","status",
       "conditionOut","conditionIn","issuedAt","dueDate","returnedAt","issuedBy",
       "issuedLocation","returnedBy","signature","notes")
    SELECT "itemId","itemUnitId","itemVariantId","officerId","quantity","status",
           "conditionOut","conditionIn","issuedAt","dueDate","returnedAt","issuedBy",
           "issuedLocation","returnedBy","signature","notes"
      FROM src ORDER BY ord
    RETURNING *
  )
  SELECT COALESCE(jsonb_agg(to_jsonb(ins) ORDER BY "id"), '[]'::jsonb)
    INTO result FROM ins;

  RETURN result;
END;
$$;

-- ---------------------------------------------------------------------------
-- return_assignment — atomic return + restock.
-- The server pre-resolves the branch (sized / serialized / bulk) and passes
-- the exact patches. Applying them together keeps the assignment update and
-- the stock restock atomic. syncItemIds triggers the unit->item re-derivation
-- for serialized returns (mirrors storage.updateUnit -> syncItemQuantity).
--
-- Payload shape:
--   { "assignmentId": int,
--     "assignmentPatch": { "status","conditionIn","returnedAt","returnedBy","notes" },
--     "variantDelta": { "id": int, "newQty": int } | null,
--     "unitPatch":    { "id": int, "status","assignedOfficerId","condition" } | null,
--     "itemPatch":    { "id": int, "quantity","status","condition" } | null,
--     "syncItemIds":  [int] }
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION return_assignment(p jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  updated  assignments;
  ap       jsonb := p->'assignmentPatch';
  sid      integer;
BEGIN
  UPDATE assignments
     SET "status"      = ap->>'status',
         "conditionIn" = ap->>'conditionIn',
         "returnedAt"  = ap->>'returnedAt',
         "returnedBy"  = ap->>'returnedBy',
         "notes"       = ap->>'notes'
   WHERE "id" = (p->>'assignmentId')::integer
   RETURNING * INTO updated;

  IF jsonb_typeof(p->'variantDelta') = 'object' THEN
    UPDATE item_variants
       SET "quantity" = (p->'variantDelta'->>'newQty')::integer
     WHERE "id" = (p->'variantDelta'->>'id')::integer;
  END IF;

  IF jsonb_typeof(p->'unitPatch') = 'object' THEN
    UPDATE item_units
       SET "status"            = p->'unitPatch'->>'status',
           "assignedOfficerId" = (p->'unitPatch'->>'assignedOfficerId')::integer,
           "condition"         = p->'unitPatch'->>'condition'
     WHERE "id" = (p->'unitPatch'->>'id')::integer;
  END IF;

  IF jsonb_typeof(p->'itemPatch') = 'object' THEN
    UPDATE items
       SET "quantity"  = (p->'itemPatch'->>'quantity')::integer,
           "status"    = p->'itemPatch'->>'status',
           "condition" = p->'itemPatch'->>'condition'
     WHERE "id" = (p->'itemPatch'->>'id')::integer;
  END IF;

  FOR sid IN
    SELECT value::integer FROM jsonb_array_elements_text(COALESCE(p->'syncItemIds', '[]'::jsonb))
  LOOP
    PERFORM sync_item_quantity(sid);
  END LOOP;

  RETURN to_jsonb(updated);
END;
$$;

-- ---------------------------------------------------------------------------
-- kit_issue — atomic kit issue.
-- Identical apply semantics to issue_batch (aggregated deltas + one assignment
-- per successfully-issued line, all pre-resolved by the server) PLUS a sync
-- pass over syncItemIds — because issuing a serialized kit line re-derives its
-- item quantity/status (mirrors the storage.updateUnit -> syncItemQuantity the
-- old kit-issue route performed per unit). Skipped lines are decided server-
-- side and never reach this function.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION kit_issue(p jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  result jsonb;
  sid    integer;
BEGIN
  UPDATE item_variants
     SET "quantity" = d."newQty"
    FROM jsonb_to_recordset(COALESCE(p->'variantDeltas', '[]'::jsonb))
           AS d("id" integer, "newQty" integer)
   WHERE item_variants."id" = d."id";

  UPDATE items
     SET "quantity" = d."newQty",
         "status"   = CASE WHEN d."setIssued" THEN 'issued' ELSE items."status" END
    FROM jsonb_to_recordset(COALESCE(p->'itemDeltas', '[]'::jsonb))
           AS d("id" integer, "newQty" integer, "setIssued" boolean)
   WHERE items."id" = d."id";

  UPDATE item_units
     SET "status" = 'issued',
         "assignedOfficerId" = d."officerId"
    FROM jsonb_to_recordset(COALESCE(p->'unitIssues', '[]'::jsonb))
           AS d("id" integer, "officerId" integer)
   WHERE item_units."id" = d."id";

  -- NOTE: jsonb_to_recordset cannot be combined with WITH ORDINALITY when a
  -- column-definition list is supplied ("WITH ORDINALITY cannot be used with a
  -- column definition list"). Expand each element with jsonb_array_elements
  -- (single jsonb column, ORDINALITY allowed) and cast fields explicitly.
  WITH src AS (
    SELECT
      (a.elem->>'itemId')::integer        AS "itemId",
      (a.elem->>'itemUnitId')::integer    AS "itemUnitId",
      (a.elem->>'itemVariantId')::integer AS "itemVariantId",
      (a.elem->>'officerId')::integer     AS "officerId",
      (a.elem->>'quantity')::integer      AS "quantity",
       a.elem->>'status'                  AS "status",
       a.elem->>'conditionOut'            AS "conditionOut",
       a.elem->>'conditionIn'             AS "conditionIn",
       a.elem->>'issuedAt'                AS "issuedAt",
       a.elem->>'dueDate'                 AS "dueDate",
       a.elem->>'returnedAt'              AS "returnedAt",
       a.elem->>'issuedBy'                AS "issuedBy",
       a.elem->>'issuedLocation'          AS "issuedLocation",
       a.elem->>'returnedBy'              AS "returnedBy",
       a.elem->>'signature'               AS "signature",
       a.elem->>'notes'                   AS "notes",
       a.ord                              AS ord
      FROM jsonb_array_elements(COALESCE(p->'assignments', '[]'::jsonb))
             WITH ORDINALITY AS a(elem, ord)
  ),
  ins AS (
    INSERT INTO assignments
      ("itemId","itemUnitId","itemVariantId","officerId","quantity","status",
       "conditionOut","conditionIn","issuedAt","dueDate","returnedAt","issuedBy",
       "issuedLocation","returnedBy","signature","notes")
    SELECT "itemId","itemUnitId","itemVariantId","officerId","quantity","status",
           "conditionOut","conditionIn","issuedAt","dueDate","returnedAt","issuedBy",
           "issuedLocation","returnedBy","signature","notes"
      FROM src ORDER BY ord
    RETURNING *
  )
  SELECT COALESCE(jsonb_agg(to_jsonb(ins) ORDER BY "id"), '[]'::jsonb)
    INTO result FROM ins;

  FOR sid IN
    SELECT value::integer FROM jsonb_array_elements_text(COALESCE(p->'syncItemIds', '[]'::jsonb))
  LOOP
    PERFORM sync_item_quantity(sid);
  END LOOP;

  RETURN result;
END;
$$;

-- ---------------------------------------------------------------------------
-- replace_kit_items — atomic "delete all lines then re-insert" for editing a
-- kit's contents (mirrors storage.replaceKitItems' transaction).
--   Payload: { "kitId": int, "lines": [{ "itemId": int, "quantity": int }] }
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION replace_kit_items(p jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_kit integer := (p->>'kitId')::integer;
BEGIN
  DELETE FROM kit_items WHERE "kitId" = v_kit;
  INSERT INTO kit_items ("kitId","itemId","quantity")
  SELECT v_kit, d."itemId", COALESCE(d."quantity", 1)
    FROM jsonb_to_recordset(COALESCE(p->'lines', '[]'::jsonb))
           AS d("itemId" integer, "quantity" integer);
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- ---------------------------------------------------------------------------
-- Data-migration helpers (used by scripts/migrate_data_to_supabase.ts).
--   truncate_all()      — --wipe: clear every table, reset identities.
--   reset_sequences()   — after an ID-preserving load, advance each identity
--                         sequence past the max imported id.
-- ---------------------------------------------------------------------------
-- SECURITY DEFINER: TRUNCATE ... RESTART IDENTITY resets identity sequences,
-- which requires ownership of those sequences. The app connects with the anon
-- role (no sequence ownership), so as SECURITY INVOKER this fails with
-- "must be owner of sequence ..._id_seq". Running as the function owner (the
-- role that applied this migration, which owns the tables/sequences) makes the
-- data-migration --wipe path work under the anon key. search_path is pinned per
-- SECURITY DEFINER hardening guidance.
CREATE OR REPLACE FUNCTION truncate_all()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  TRUNCATE users, officers, items, item_units, item_variants,
           assignments, kits, kit_items, audit_log
    RESTART IDENTITY CASCADE;
END;
$$;

-- SECURITY DEFINER: setval() requires UPDATE on the target sequence, which the
-- anon role lacks. See truncate_all above.
CREATE OR REPLACE FUNCTION reset_sequences()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','officers','items','item_units','item_variants',
                           'assignments','kits','kit_items','audit_log']
  LOOP
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, %L),
                     COALESCE((SELECT max("id") FROM %I), 1),
                     (SELECT max("id") FROM %I) IS NOT NULL)',
      t, 'id', t, t);
  END LOOP;
END;
$$;
