import { jsPDF } from "jspdf";

/* ------------------------------------------------------------------ *
 * Shared jsPDF helpers for Batch 3 reports. Same plain-text layout
 * approach as the Batch 1 receipts (client/src/lib/receipt.ts) — no
 * autotable dependency. Letter size, UFPD header, generation stamp,
 * page numbers. Every report builder in this folder uses these.
 * ------------------------------------------------------------------ */

export const MARGIN = 14;
export const LINE = 6;

export function genStamp(): string {
  return new Date().toLocaleString("en-US", {
    year: "numeric", month: "short", day: "numeric", hour: "numeric", minute: "2-digit",
  });
}

/** New letter-size portrait document (mm units). */
export function newDoc(orientation: "portrait" | "landscape" = "portrait"): jsPDF {
  return new jsPDF({ unit: "mm", format: "letter", orientation });
}

export function pageW(doc: jsPDF): number { return doc.internal.pageSize.getWidth(); }
export function pageH(doc: jsPDF): number { return doc.internal.pageSize.getHeight(); }

/**
 * Draw the standard report header. Returns the y cursor below it.
 * Left: UFPD Quartermaster. Center: report title (+ optional subtitle).
 * Right: generation timestamp.
 */
export function reportHeader(doc: jsPDF, title: string, subtitle?: string): number {
  const w = pageW(doc);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("UFPD Quartermaster", MARGIN, 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(`Generated ${genStamp()}`, w - MARGIN, 16, { align: "right" });
  doc.setTextColor(0);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, w / 2, 24, { align: "center" });
  let y = 30;
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text(subtitle, w / 2, y, { align: "center" });
    doc.setTextColor(0);
    y += 6;
  }
  doc.setDrawColor(170);
  doc.line(MARGIN, y, w - MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  return y + 6;
}

/** Page "x of y" + attribution footer applied to every page. Call last. */
export function reportFooter(doc: jsPDF): void {
  const w = pageW(doc);
  const h = pageH(doc);
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text("Generated by UFPD Quartermaster", MARGIN, h - 8);
    doc.text(`Page ${p} of ${pages}`, w - MARGIN, h - 8, { align: "right" });
    doc.setTextColor(0);
  }
}

export type Col = { header: string; width: number; align?: "left" | "right" | "center" };

/**
 * Hand-rolled table with word-wrap and automatic pagination (re-drawing the
 * header row on each new page). Returns the y cursor below the last row.
 * `subtitle` (optional) is re-printed under the header on continuation pages.
 */
export function drawTable(
  doc: jsPDF,
  startY: number,
  cols: Col[],
  rows: (string | number)[][],
  opts: { fontSize?: number; headerFill?: boolean } = {},
): number {
  const fontSize = opts.fontSize ?? 9;
  const h = pageH(doc);
  const xs: number[] = [];
  let acc = MARGIN;
  for (const c of cols) { xs.push(acc); acc += c.width; }
  const tableRight = acc;

  function drawHeader(y: number): number {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(fontSize);
    if (opts.headerFill) {
      doc.setFillColor(238, 238, 238);
      doc.rect(MARGIN, y - 4, tableRight - MARGIN, 6, "F");
    }
    cols.forEach((c, i) => {
      const tx = c.align === "right" ? xs[i] + c.width - 1 : c.align === "center" ? xs[i] + c.width / 2 : xs[i];
      doc.text(c.header, tx, y, { align: c.align ?? "left" });
    });
    y += 2;
    doc.setDrawColor(150);
    doc.line(MARGIN, y, tableRight, y);
    return y + 4;
  }

  let y = drawHeader(startY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(fontSize);

  for (const row of rows) {
    // wrap each cell, compute row height
    const wrapped = row.map((cell, i) => doc.splitTextToSize(String(cell ?? ""), cols[i].width - 2));
    const lines = Math.max(1, ...wrapped.map((w) => w.length));
    const rowH = lines * (LINE - 1) + 1;
    if (y + rowH > h - 16) {
      doc.addPage();
      y = drawHeader(20);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(fontSize);
    }
    wrapped.forEach((cellLines, i) => {
      const c = cols[i];
      const tx = c.align === "right" ? xs[i] + c.width - 1 : c.align === "center" ? xs[i] + c.width / 2 : xs[i];
      doc.text(cellLines, tx, y, { align: c.align ?? "left" });
    });
    y += rowH;
    doc.setDrawColor(225);
    doc.line(MARGIN, y - 3, tableRight, y - 3);
  }
  return y;
}

/** Empty check box for print check-off. */
export function checkbox(doc: jsPDF, x: number, y: number, size = 4): void {
  doc.setDrawColor(80);
  doc.setLineWidth(0.3);
  doc.rect(x, y - size + 1, size, size);
}

/** A labeled blank line (for handwritten fields). Returns y after the line. */
export function blankLine(doc: jsPDF, y: number, label: string, x = MARGIN, lineWidth = 80): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(label, x, y);
  const lw = doc.getTextWidth(label);
  doc.setDrawColor(120);
  doc.line(x + lw + 3, y + 0.5, x + lw + 3 + lineWidth, y + 0.5);
  doc.setFont("helvetica", "normal");
  return y + LINE + 1;
}

export function sectionTitle(doc: jsPDF, y: number, text: string): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(text, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  return y + LINE;
}
